In [ ]:
# Bismilla hir rehman nir raheem

## 1.1 **Dtensors**

In [ ]:
# Tensors are essential part of Pytorch

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
# Plotting Vectors

In [4]:
def plotVec(vectors):
    ax = plt.axes()
    
    # For loop to draw the vectors
    for vec in vectors:
        ax.arrow(0, 0, *vec["vector"], head_width = 0.05,color = vec["color"], head_length = 0.1)
        plt.text(*(vec["vector"] + 0.1), vec["name"])
    
    plt.ylim(-2,2)
    plt.xlim(-2,2)

In [ ]:
# Making tensor out of a list

In [15]:
tensorA = torch.tensor([1,2,3,4,5])
print(tensorA.dtype)
tensorA.type()
# type(tensorA)      # Use the above command instead of this to check type

torch.int64


'torch.LongTensor'

In [22]:
tensorB = torch.Tensor([1.0,2,3,4.0,5])
print(tensorB.dtype)
tensorB.type()

torch.float32


'torch.FloatTensor'

In [21]:
print(tensorA)

tensor([1, 2, 3, 4, 5])


In [4]:
# Converting Integer list to Float tensor

# Method 1:
tensorC = torch.FloatTensor([0,1,2,3,4])
tensorC.dtype
print(tensorC.type())
print(tensorC)

# Method 2:
print('Method 2:')
tensorD = torch.tensor([0,1,2,3,4,5])
tensorE = tensorD.type(torch.FloatTensor)
tensorE.type()
#print(tensorE)

torch.FloatTensor
tensor([0., 1., 2., 3., 4.])
Method 2:


'torch.FloatTensor'

In [50]:
# Checking size and dimension of the tensor:
#    .size()
#    .ndimension()
print(tensorE.size())
tensorE.ndimension()

torch.Size([6])


1

In [51]:
# Zindagi me ksi cheez se ghabrana nhe, ye HATIM ka qoul hai.

In [52]:
# New schedule from tomorrow

In [6]:
# Reshaping a tensor:
#           .view(row, column)
tensorE_2d = tensorE.view(6,1)
print(tensorE)
print(tensorE_2d)
# Here the size is changed from 6 to 6X1.
# And the dimension changed from 1d to 2d
print(tensorE_2d.size())
print(tensorE_2d.ndimension())

tensor([0., 1., 2., 3., 4., 5.])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]])
torch.Size([6, 1])
2


In [10]:
# Reshaping a tensor of dynamic size
# Use view with -1 as one argument.
tensorE_2d = tensorE.view(-1,1)
print(tensorE)
print(tensorE_2d)
print(tensorE_2d.size())
print(tensorE_2d.ndimension())

tensor([0., 1., 2., 3., 4., 5.])
tensor([[0.],
        [1.],
        [2.],
        [3.],
        [4.],
        [5.]])
torch.Size([6, 1])
2


In [3]:
# Converting **numpy array** to tensor
# Use torch.from_numpy(numpy_array)

n1 = np.array([1.0,2.0,3.0,4])
tensor_z1 = torch.from_numpy(n1)
print(tensor_z1)
print(tensor_z1.type())
print(tensor_z1.dtype)

# Just my wish:
tensor_z2 = torch.FloatTensor(n1)
print(tensor_z2)
print(tensor_z2.type())
print(tensor_z2.dtype)

tensor([1., 2., 3., 4.], dtype=torch.float64)
torch.DoubleTensor
torch.float64
tensor([1., 2., 3., 4.])
torch.FloatTensor
torch.float32


In [26]:
# Converting tensor to numpy
#             .numpy()

n2 = tensor_z1.numpy()
n3 = tensor_z2.numpy()
print(n2,'\n',n3)
print(n2.dtype)
print(n3.dtype)

[1. 2. 3. 4.] 
 [1. 2. 3. 4.]
float64
float32


In [30]:
# The problem is that n2 points to tensor_z1, and tensor_z1 points back to n1.
# eg:
n1[:] = 0
print(n1)
print(tensor_z1)
print(n2)
# Pointing doesn't takes place if tensor is made from numpy array using torch.FloatTensor(n1) or torch.LongTensor(n1) or Double.
print(tensor_z2)
print(n3)

[0. 0. 0. 0.]
tensor([0., 0., 0., 0.], dtype=torch.float64)
[0. 0. 0. 0.]
tensor([1., 2., 3., 4.])
[1. 2. 3. 4.]


In [36]:
# Just for my wish:
tensorC = torch.LongTensor([0,1.0,2,3.0,4])
print(tensorC.dtype)
print(tensorC.type())
print(tensorC)

torch.int64
torch.LongTensor
tensor([0, 1, 2, 3, 4])


In [6]:
# Converting pandas series to tensor
pandas_series=pd.Series([0.1, 2, 0.3, 10.1], index = [1,2,3,4])


1     0.1
2     2.0
3     0.3
4    10.1
dtype: float64