In [2]:
import torch

In [16]:
A = [[11,12,13],[21,22,23],[31,32,33]]
tensor_a = torch.tensor(A)
tensor_a.numel()

9

In [28]:
tensor_ques = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
tens_ques_slice =[[1:3, 1]] #(syntax error here)
#tensor_ques[tens_ques_slice] = 0
#tensor_ques[1:3, 1] = 0
tensor_ques

SyntaxError: invalid syntax (<ipython-input-28-9d8c7a9c2d08>, line 2)

#### **Starting the game now**

In [2]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

##### Types and Shapes

In [30]:
twoD_list = [[11, 12, 13], [21, 22, 23], [31, 32, 33]]
twoD_tensor = torch.tensor(twoD_list)
print("The New 2D Tensor: ", twoD_tensor)

The New 2D Tensor:  tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


In [37]:
print(twoD_tensor.ndimension())
print(twoD_tensor.shape)
print(twoD_tensor.numel())
print(twoD_tensor.dtype)

2
torch.Size([3, 3])
9
torch.int64


In [46]:
# Convert tensor to numpy array; Convert numpy array to tensor
n1 = twoD_tensor.numpy()
print(n1)
type(n1)

twod_tensor2 = torch.from_numpy(n1)
print('')
print(twod_tensor2)
type(twod_tensor2)

[[11 12 13]
 [21 22 23]
 [31 32 33]]

tensor([[11, 12, 13],
        [21, 22, 23],
        [31, 32, 33]])


torch.Tensor

In [53]:
twoD_tensor[1,1] = 0
print(twoD_tensor)
print(n1)
print(twod_tensor2)
# NOTE here that n1 and twod_tensor2 are attaining the form of twoD_tensor automatically.

tensor([[11, 12, 13],
        [21,  0, 23],
        [31, 32, 33]])
[[11 12 13]
 [21  0 23]
 [31 32 33]]
tensor([[11, 12, 13],
        [21,  0, 23],
        [31, 32, 33]])


In [61]:
# Converting pandas dataframe to a tensor
pddf1 = pd.DataFrame({'a':[1,2,3], 'b':[4,5,6]})
pddf1.values
pddf1.values.dtype
type(pddf1.values)

tensor_b = torch.from_numpy(pddf1.values)
tensor_b

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [64]:
# Practice: try to convert Pandas Series to tensor

df = pd.DataFrame({'A':[11, 33, 22],'B':[3, 3, 2]})
tensor_c = torch.from_numpy(df.values)
tensor_c

tensor([[11,  3],
        [33,  3],
        [22,  2]])

##### Indexing and Slicing

In [66]:
# How to access
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1, 2])
print("What is the value on 2nd-row 3rd-column? ", tensor_example[1][2])

What is the value on 2nd-row 3rd-column?  tensor(23)
What is the value on 2nd-row 3rd-column?  tensor(23)


In [67]:
# How to access multiple values
tensor_example = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
print("What is the value on 1st-row first two columns? ", tensor_example[1,0:2])
print("What is the value on 1st-row first two columns? ", tensor_example[1][0:2])

What is the value on 1st-row first two columns?  tensor([21, 22])
What is the value on 1st-row first two columns?  tensor([21, 22])


In [69]:
# Try to change the values on the second column and the last two rows to 0. 
# Basically, change the values on tensor_ques[1][1] and tensor_ques[2][1] to 0.

# Practice: Use slice and index to change the values on the matrix tensor_ques.


tensor_ques = torch.tensor([[11, 12, 13], [21, 22, 23], [31, 32, 33]])
tensor_ques[1:3,1] = 0
tensor_ques

tensor([[11, 12, 13],
        [21,  0, 23],
        [31,  0, 33]])

##### **Tensor Operations**

In [3]:
X = torch.tensor([[1, 0],[0, 1]]) 
Y = torch.tensor([[2, 1],[1, 2]])
tensor_d = X+Y
tensor_d

tensor([[3, 1],
        [1, 3]])

In [4]:
Y = torch.tensor([[2, 1], [1, 2]]) 
two_Y = 2 * Y
print("The result of 2Y: ", two_Y)

The result of 2Y:  tensor([[4, 2],
        [2, 4]])


In [5]:
X = torch.tensor([[1, 0], [0, 1]])
Y = torch.tensor([[2, 1], [1, 2]]) 
X_times_Y = X * Y
print("The result of X * Y: ", X_times_Y)

The result of X * Y:  tensor([[2, 0],
        [0, 2]])


In [7]:
# Matrix Multiplication
A = torch.tensor([[0, 1, 1], [1, 0, 1]])
B = torch.tensor([[1, 1], [1, 1], [-1, 1]])
print(A)
print(B)
AB = torch.mm(A,B)
print(AB)

tensor([[0, 1, 1],
        [1, 0, 1]])
tensor([[ 1,  1],
        [ 1,  1],
        [-1,  1]])
tensor([[0, 2],
        [0, 2]])


In [13]:
# # Matrix Multiplication by me:
A = torch.tensor([[10,20,10], [4,5,6], [2,3,5]])
B = torch.tensor([[3,2,4], [3,3,9], [4,4,2]])
print('A: ',A)
print('B: ',B,'\n')
AB = torch.mm(A,B)
print(AB)

elem_AB = A*B
print(elem_AB)

A:  tensor([[10, 20, 10],
        [ 4,  5,  6],
        [ 2,  3,  5]])
B:  tensor([[3, 2, 4],
        [3, 3, 9],
        [4, 4, 2]]) 

tensor([[130, 120, 240],
        [ 51,  47,  73],
        [ 35,  33,  45]])
tensor([[30, 40, 40],
        [12, 15, 54],
        [ 8, 12, 10]])


In [15]:
# Practice:
X = torch.tensor([[0, 1], [1, 2]])
Y = torch.tensor([[-1, -2, 0], [2, 1, 2]])
print(X)
print(Y)
# my ans: [2, 1, 2],[3, 0, 4]
XY = torch.mm(X,Y)
print(XY)

tensor([[0, 1],
        [1, 2]])
tensor([[-1, -2,  0],
        [ 2,  1,  2]])
tensor([[2, 1, 2],
        [3, 0, 4]])


#### I am very **happy** that my answers are correct. **Thank You** very much!

##        ################ ***THE END*** ################# #####